version: "3.9"

services:
  notes:
    build: ./
    container_name: notes
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - bridged_network
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/notes'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
  #   https://hub.docker.com/_/postgres
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - bridged_network

networks:
  bridged_network:
    driver: bridge