version: "3.9"

services:
  #   https://hub.docker.com/_/postgres
  database:
    image: postgres:13.12-alpine3.18
    container_name: notes-db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - bridged_network

networks:
  bridged_network:
    driver: bridge