server:
  port: 8088

spring:
  application:
    name: notes
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    database-change-log-lock-table: NOTES_DATABASECHANGELOGLOCK

general:
  note:
    page-size: ${GENERAL_NOTE_PAGESIZE:15}
  category:
    page-size: ${GENERAL_CATEGORY_PAGESIZE:15}




