-- liquibase formatted sql

-- changeset ashabelskii:1
CREATE TABLE note
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR,
    CONSTRAINT pk_note PRIMARY KEY (id)
);

-- changeset ashabelskii:2
CREATE TABLE category
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

ALTER TABLE note
    ADD category_id BIGINT;
ALTER TABLE note
    ADD CONSTRAINT FK_NOTE_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);
